/************************************************/
/* NOTE TO THE READER:  The code template below */
/* contains only the code generated by the SOM  */
/* compiler, not the code that the programmer   */
/* would add to complete the implementation.    */
/************************************************/

/*
 * This file was generated by the SOM Compiler.
 * FileName: calc.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define calculator_Class_Source
#include "calc.ih"

/*
 *  Method Name:  Add
 *    This method returns the sum of the two input
 *    numbers.
 *
 */

SOM_Scope signed long   SOMLINK Add(calculator *somSelf,
                signed long var1,
                signed long var2)
{
    calculatorData *somThis = calculatorGetData(somSelf);
    calculatorMethodDebug("calculator","Add");

    return (signed long) 0;
}

/*
 *  Method Name:  Subtract
 *    This method returns the value of
 *    var1 minus var2
 *
 */

SOM_Scope signed long   SOMLINK Subtract(calculator *somSelf,
                signed long var1,
                signed long var2)
{
    calculatorData *somThis = calculatorGetData(somSelf);
    calculatorMethodDebug("calculator","Subtract");

    return (signed long) 0;
}

