/*
 * This file was generated by the SOM Compiler.
 * FileName: fanccalc.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define fcalc_Class_Source
#include "fanccalc.ih"

/*
 *  Method Name:  Multiply
 *   This method returns the product of the two input numbers
 *
 */

SOM_Scope signed long   SOMLINK Multiply(fcalc *somSelf,
                signed long var1,
                signed long var2)
{
    /* fcalcData *somThis = fcalcGetData(somSelf); */
    fcalcMethodDebug("fcalc","Multiply");

    return var1 * var2;
}

/*
 *  Method Name:  Divide
 *    This method returns the result of dividing the first
 *    number by the second.  It will return 0 if the second
 *    number is 0.
 *
 */

SOM_Scope double   SOMLINK Divide(fcalc *somSelf,
                signed long var1,
                signed long var2)
{
    double res;

    /* fcalcData *somThis = fcalcGetData(somSelf); */
    fcalcMethodDebug("fcalc","Divide");

    if (var2 == 0) {
       res = (double) 0;
    } else {
       res = var1 / var2;
    }

    return res;
}
