 /*
  * This file was generated by the SOM Compiler.
  * FileName: fifoq.c.
  * Generated using:
  *     SOM Precompiler spc: 3.9
  *     SOM Emitter emitc: 2.3
  */

#define FIFOQ_Class_Source
#include "fifoq.ih"

/*
 *                   Adds an item to the list
 */

SOM_Scope INT   SOMLINK AddItem(FIFOQ *somSelf,
        PVOID *pItem)
{
    INT rc;

    /* FIFOQData *somThis = FIFOQGetData(somSelf); */
    FIFOQMethodDebug("FIFOQ","AddItem");

    rc = _AddPos(somSelf, pItem, 'T');
    return rc;
}
