/*
 * This file was generated by the SOM Compiler.
 * FileName: fifoq_1.c.
 * Generated using:
 *     SOM Precompiler spc: 3.9
 *     SOM Emitter emitc: 2.3
 */

#define FIFOQ_Class_Source
#include "fifoq_1.ih"

/*
 *                   Adds an item to the list
 */

SOM_Scope INT   SOMLINK AddItem(FIFOQ *somSelf,
                PVOID *pItem)
{
    pListItem   pNewItem;
    INT         rc = 0;

    FIFOQData *somThis = FIFOQGetData(somSelf);
    FIFOQMethodDebug("FIFOQ","AddItem");

    do {
          /* Allocate space for a new ListItem   */
       pNewItem = SOMMalloc(sizeof(ListItem)-sizeof(UCHAR) +
                         _usListItemSize);
       if (!pNewItem) {
          rc = MEMORY_ERROR;
          break;
       }

          /* Initialize the new Item */
       memcpy(&pNewItem->cData, pItem, _usListItemSize);
       pNewItem->pNext = (pListItem) NULL;
       pNewItem->pPrev = _pListTail;

          /* Add the new Item to the end of the List */
       if (_bListEmptyFlag == LIST_IS_EMPTY) {
          _pListHead = _pListTail = pNewItem;
          _bListEmptyFlag = LIST_NOT_EMPTY;
       } else {
          _pListTail->pNext = pNewItem;
          _pListTail = pNewItem;
       }

    } while (0); /* enddo */

    return rc;
}

/*
 *                   Removes the current item from
 *                   the list and returns it
 */

SOM_Scope PVOID   SOMLINK GetItem(FIFOQ *somSelf)
{
    PVOID      retItem = NULL;
    pListItem  pSaveItem;

    FIFOQData *somThis = FIFOQGetData(somSelf);
    FIFOQMethodDebug("FIFOQ","GetItem");

    do {
       /* Error if the list is empty            */
       if (_bListEmptyFlag == LIST_IS_EMPTY) {
          break;
       }

       /* Copy the item from head of the chain   */
       /* Allocate return buffer   */
       retItem = (PVOID) SOMMalloc( _usListItemSize);
       if (!retItem) {
          break;
       }
       memcpy(retItem, &_pListHead->cData, _usListItemSize);

       /* Remove the item from the list  */
       /* Cases: 1 item in the list      */
       /*        > 1 item in the list    */

       if (_pListHead == _pListTail) {
          /* Only one item in the list */
          _pListHead = _pListTail = (pListItem)  NULL;
          _bListEmptyFlag = LIST_IS_EMPTY;
       } else {
          _pListHead = _pListHead->pNext;
          _pListHead->pPrev = (pListItem) NULL;
       }

       /* Now free the list item itself */
       SOMFree(pSaveItem);

    } while (0 ); /* enddo */

    return retItem;
}

SOM_Scope void   SOMLINK somInit(FIFOQ *somSelf)
{
    FIFOQData *somThis = FIFOQGetData(somSelf);
    FIFOQMethodDebug("FIFOQ","somInit");

    parent_somInit(somSelf);

    _pListHead = _pListTail = (pListItem) NULL;
    _usListItemSize = 1;
    _bListEmptyFlag = LIST_IS_EMPTY;

}

SOM_Scope void   SOMLINK somUninit(FIFOQ *somSelf)
{
    FIFOQData *somThis = FIFOQGetData(somSelf);
    FIFOQMethodDebug("FIFOQ","somUninit");

    while (_bListEmptyFlag != LIST_IS_EMPTY) {
       _GetItem(somSelf);
    } /* endwhile */

    parent_somUninit(somSelf);
}
