/*
 * This file was generated by the SOM Compiler.
 * FileName: metacalc.c.
 * Generated using:
 *     SOM Precompiler spc: 1.22
 *     SOM Emitter emitc: 1.24
 */

#define calculator_Class_Source
#include "metacalc.ih"

/*
 *  Method Name:  Add
 *    This method returns the sum of the two input
 *    numbers.
 *
 */

SOM_Scope signed long   SOMLINK calcpreAdd(calculator *somSelf,
                signed long var1,
                signed long var2)
{
    calculatorData *somThis = calculatorGetData(somSelf);
    calculatorMethodDebug("calculator","calcpreAdd");

    /* increment the class instance data            */
    /* Notice the use of the macro to reference the */
    /*    class object                              */
    _Register1 = get_NumAddCalls(_calculator);
    get_NumAddCalls(_calculator) = _Register1 + 1;

    /* set the instance data */
    _Register1 = var1;
    _Register2 = var2;

    return (_Register1 + _Register2);
}

/*
 *  Method Name:  Subtract
 *    This method returns the value of
 *    var1 minus var2
 *
 */

SOM_Scope signed long   SOMLINK calcpreSubtract(calculator *somSelf,
                signed long var1,
                signed long var2)
{
    calculatorData *somThis = calculatorGetData(somSelf);
    calculatorMethodDebug("calculator","calcpreSubtract");

    return var1 - var2;
}

#undef SOM_CurrentClass
#define SOM_CurrentClass SOMMeta
/*
 *  Override it to increment NumCalcs
 */

SOM_Scope SOMAny *  SOMLINK metacalcsomNew(M_calculator *somSelf)
{
    M_calculatorData *somThis = M_calculatorGetData(somSelf);
    M_calculatorMethodDebug("M_calculator","metacalcsomNew");

    _NumCalcs++;
    return (parent_somNew(somSelf));
}

/*
 *  Override it to initialize data variables
 */

SOM_Scope void   SOMLINK metacalcsomInit(M_calculator *somSelf)
{
    M_calculatorData *somThis = M_calculatorGetData(somSelf);
    M_calculatorMethodDebug("M_calculator","metacalcsomInit");

    /* Call the parent first!!!!  */
    parent_somInit(somSelf);

    /* Then initialize data variables */
    _NumCalcs = 0;
    _NumAddCalls = 0;
}
