/*
 * This file was generated by the SOM Compiler.
 * FileName: strng.c.
 * Generated using:
 *     SOM Precompiler spc: 3.9
 *     SOM Emitter emitc: 2.3
 */

#define String_Class_Source
#include "strng.ih"

/*
 *  Set the string
 */

SOM_Scope int   SOMLINK setString(String *somSelf,
          char *ps)
{
    int rc = 0;

    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","setString");

    do {
       /* If a null pointer was passed, return error */
       /* Otherwise, clear any previous value,       */
       /* Allocate memory and set the instance data  */
       /* (Instance data are _str and _str_len )     */
       if (ps == NULL) {
          rc = INVALID_PARAMETER;
          break;
       }
       _clearString(somSelf);

       _str_len = strlen(ps);

       _str = SOMMalloc((_str_len)+1);
       if (_str == NULL) {
          rc = MEMORY_ERROR;
          break;
       }
       strcpy(_str, ps);
    } while(0);     /* Fall out of do loop */

    return rc;
}

/*
 *  Return the string value
 */

SOM_Scope char *  SOMLINK getString(String *somSelf)
{
    char * tmp = NULL;

    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","getString");

    do {
       if (_str == NULL) {
          break;
       }
       tmp = SOMMalloc((_str_len)+1);
       if (!tmp) {
          break;
       }
       strcpy(tmp, _str);

    } while(0);     /* Fall out of do loop */
    return tmp;
}


/*
 *  Clear the string
 */

SOM_Scope void  SOMLINK clearString(String *somSelf)
{
    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","clearString");

    // Free any allocated memory and reset the instance data
    SOMFree(_str);
    _str_len = 0;
    _str = NULL;
    return;
}


/*
 *  Return the length of the string
 */

SOM_Scope int   SOMLINK getStringLen(String *somSelf)
{
    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","getStringLen");

    /* The length is stored as instance data */
    return (int) _str_len;
}

/*
 *  Initialize the object
 */

SOM_Scope void   SOMLINK somInit(String *somSelf)
{
    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","somInit");

    parent_somInit(somSelf);    // Call the parent first

    _str_len = 0;               // Then initialize instance
    _str = NULL;                // data
}

/*
 *  Uninitialize the object
 */

SOM_Scope void   SOMLINK somUninit(String *somSelf)
{
    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","somUninit");

    if (_str != NULL) {         // Free any memory allocated
       SOMFree(_str);           // for this object
    }
    parent_somUninit(somSelf);  // Call the parent last
}

/*
 *  Dumps object instance data
 */

SOM_Scope void   SOMLINK somDumpSelfInt(String *somSelf,
          int level)
{
    StringData *somThis = StringGetData(somSelf);
    StringMethodDebug("String","somDumpSelfInt");

    // Dump instance data after ancestors dump theirs
    parent_somDumpSelfInt(somSelf,level);

    somPrintf("\n str_len=%d", _str_len);
    somPrintf("\n str    =%s", _str);
}
